name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12:30 AM IST (7 PM UTC previous day)
    - cron: "30 18 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_LINES_OF_CODE: true
          SHOW_SHORT_INFO: true
          SHOW_LOC_CHART: false
          SHOW_PROJECTS: true
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_EDITORS: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_COMMIT: true
          SHOW_TIMEZONE: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_UPDATED_DATE: true
          COMMIT_MESSAGE: "ðŸ“Š Updated Dev Metrics"
          SYMBOL_VERSION: 1
